import EstimateUploadTab from './EstimateUploadTab'
import ScheduleATab from './ScheduleATab'
import type { ExcelTable } from '@core/types'

interface Props {
  tables: ExcelTable[]
  onChange: (table: ExcelTable) => void
}

/**
 * One workspace for everything derived from an estimate — BOQ, Schedule A,
 * Deviation Statement, and Material Quantity all come from the same
 * uploaded estimate's items, so there's no reason to upload it three or
 * four times across separate tabs. Below the main upload sits one alternate
 * starting point: an existing BOQ (for Schedule A alone, when the BOQ wasn't
 * generated by this app and so has no estimate to re-derive it from).
 * Reading an estimate from photos / a scanned PDF lives on the Tools page.
 */
export default function EstimateWorkspaceTab({ tables, onChange }: Props) {
  return (
    <>
      <EstimateUploadTab tables={tables} onChange={onChange} />

      <div className="workspace-section">
        <div className="workspace-section-title">Have an Existing BOQ Instead?</div>
        <div className="workspace-section-hint">
          For a BOQ from outside this app (so there's no original estimate to upload) — generates just its Schedule A.
        </div>
        <ScheduleATab tables={tables} />
      </div>
    </>
  )
}
