import EstimateUploadTab from './EstimateUploadTab'
import UploadPhotosTab from './UploadPhotosTab'
import ScheduleATab from './ScheduleATab'
import type { ExcelTable } from '@core/types'

interface Props {
  tables: ExcelTable[]
  onChange: (table: ExcelTable) => void
}

/**
 * One workspace for everything derived from an estimate — BOQ, Schedule A,
 * Deviation Statement, and Material Quantity all come from the same
 * uploaded estimate's items, so there's no reason to upload it three or
 * four times across separate tabs. Two alternate starting points sit below
 * the main upload: photos/PDF of a paper estimate (OCR'd, then reviewed
 * before the same four downloads apply), and an existing BOQ (for Schedule
 * A alone, when the BOQ wasn't generated by this app and so has no
 * estimate to re-derive it from).
 */
export default function EstimateWorkspaceTab({ tables, onChange }: Props) {
  return (
    <>
      <EstimateUploadTab tables={tables} onChange={onChange} />

      <div className="workspace-section">
        <div className="workspace-section-title">Or Upload Photos / PDF of a Paper Estimate</div>
        <div className="workspace-section-hint">
          No digital estimate on hand — read one from photos or a scanned PDF instead, with a chance to review before
          downloading.
        </div>
        <UploadPhotosTab tables={tables} onChange={onChange} />
      </div>

      <div className="workspace-section">
        <div className="workspace-section-title">Have an Existing BOQ Instead?</div>
        <div className="workspace-section-hint">
          For a BOQ from outside this app (so there's no original estimate to upload) — generates just its Schedule A.
        </div>
        <ScheduleATab tables={tables} />
      </div>
    </>
  )
}
